# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-10-09 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0041_auto_20170823_1855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Data di protocollazione')),
                ('block_new_version', models.BooleanField(default=True, help_text='Do not allow new version of this document to be uploaded.', verbose_name='Block new version upload')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.Document', verbose_name='Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Protocollazione documento',
                'verbose_name_plural': 'Protocollazione documenti',
            },
        ),
        migrations.CreateModel(
            name='DocumentRegisterIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Protocollazione documento in entrata',
                'verbose_name_plural': 'Protocollazione documenti in entrata',
            },
        ),
        migrations.CreateModel(
            name='DocumentRegisterOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Protocollazione documento in entrata',
                'verbose_name_plural': 'Protocollazione documenti in entrata',
            },
        ),
    ]
