version: "2.3"
services:

  redis:
    image: redis:alpine

  mysql:
    image: mysql:5.7
    #volumes:
    #  - db-data:/var/lib/postgresql/data
    environment:
      MYSQL_ROOT_PASSWORD: serin

  paper:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - redis
      - mysql
    environment:
      DATABASE_NAME: mayan_edms
      DATABASE_USER: root
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_PASS: FILLME
      REDIS_URL: "redis://redis:6379/0"
