FROM python:2-alpine3.7

ENV ALPINE_VERSION 3.7

WORKDIR /usr/src/app

COPY ./requirements ./requirements/

RUN echo "http://dl-cdn.alpinelinux.org/alpine/v$ALPINE_VERSION/community" >> /etc/apk/repositories \
	&& apk add --no-cache gcc g++ graphviz libjpeg libmagic libpng-dev linux-headers musl-dev \
	libreoffice tiff-dev ghostscript gnupg poppler-utils tesseract-ocr tesseract-ocr-data-fra libzmq supervisor \
    && pip install --no-cache-dir -r requirements/production.txt \
    && apk del --purge --no-cache musl-dev linux-headers gcc g++

ENV REDIS_URL "redis://127.0.0.1:6379/0"
ENV DJANGO_SETTINGS_MODULE "mayan.settings.production"

COPY . .

RUN ./manage.py collectstatic --noinput

EXPOSE 8000

CMD supervisord -n -c /usr/src/app/supervisord-sqlite.ini
